# Path to your oh-my-zsh installation.
export ZSH="~/.oh-my-zsh"

ZSH_THEME="robbyrussell"

# Uncomment the following line to disable auto-setting terminal title.
DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
COMPLETION_WAITING_DOTS="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(
  git
  zsh-syntax-highlighting
)

# Auto Upgrage
DISABLE_UPDATE_PROMPT="true"


source $ZSH/oh-my-zsh.sh

if [ -e "/usr/local/bin/virtualenvwrapper_lazy.sh" ]; then
    source /usr/local/bin/virtualenvwrapper_lazy.sh
fi


## ALIAS ##

### GIT ###
alias shortlog='git log --date=short --pretty=format:"[ %C(bold blue)%h%Creset ] - %cd || <%Cgreen%an%Creset> %Cred->%Creset %s"'
alias gpr='git pull --rebase -v origin $(current_branch)'
alias gch='git checkout'
alias gst='git status'
alias gdf='git diff'
alias gitgraph="git log --all --pretty='format:%d %Cgreen%h%Creset %an - %s' --graph"
alias gtag='git tag --sort version:refname'
alias gsu='git submodule update'
alias gb='git branch -avv'
alias gprs='git push store $(current_branch)'


### COMMON ###
alias rede="ifconfig en1 | grep inet | grep -v inet6 | awk -F' ' '{print \$2}'"
alias la="ls -lah"


### To Programming ###

alias findpdb='grep -r "pdb" * | grep -v "#" | cut -d :  -f 1 | sort | uniq | grep ".py$"'
alias findipdb='grep -r "ipdb" * | grep -v "#" | cut -d :  -f 1 | sort | uniq | grep ".py$"'
alias psaux='ps aux | grep -v grep | grep'
