# Fig pre block. Keep at the top of this file.
[[ -f "$HOME/.fig/shell/zshrc.pre.zsh" ]] && builtin source "$HOME/.fig/shell/zshrc.pre.zsh"
# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load. Optionally, if you set this to "random"
# it'll load a random theme each time that oh-my-zsh is loaded.
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
ZSH_THEME="personalizado"

# Uncomment the following line to disable auto-setting terminal title.
DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
COMPLETION_WAITING_DOTS="true"

plugins=(
  alias-tips
  autoupdate
  git
  git-extras
  git-flow
  gitfast
  gitgo
  nvm
  macos
  python
  timer
  # yarn-autocompletions
  # zsh-autosuggestions
  zsh-navigation-tools
  zsh-nvm
  zsh-syntax-highlighting
)
autoload -U compinit && compinit

export NVM_AUTO_USE=true
# Auto upgdate plugins everyday
export UPDATE_ZSH_DAYS=1

# Auto Upgrage
DISABLE_UPDATE_PROMPT="true"

SPACESHIP_DIR_TRUNC_REPO=False

TIMER_FORMAT='[%d]'
TIMER_PRECISION=2

source $ZSH/oh-my-zsh.sh
source "$HOME/.config/znt/zsh-navigation-tools/zsh-navigation-tools.plugin.zsh"

if [ -e "/usr/local/bin/virtualenvwrapper_lazy.sh" ]; then
    source /usr/local/bin/virtualenvwrapper_lazy.sh
fi

export ANDROID_HOME="$HOME/Library/Android/sdk"
export PATH="$PATH:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools"

## ALIAS ##

### GIT ###
alias shortlog='git log --date=short --pretty=format:"[ %C(bold blue)%h%Creset ] - %cd || <%Cgreen%an%Creset> %Cred->%Creset %s"'
alias gpr='git pull --rebase -v origin $(current_branch)'
alias gch='git checkout'
alias gst='git status'
alias gdf='git diff --color-words'
alias gitgraph="git log --all --pretty='format:%d %Cgreen%h%Creset %an - %s' --graph"
alias gtag='git tag --sort version:refname'
alias gsu='git submodule update'
alias gb='git branch -avv'

### COMMON ###
alias rede="ifconfig en0 | grep inet | grep -v inet6 | awk -F' ' '{print \$2}'"
alias la="ls -lah"
alias descompacta='unrar e'
alias sizeOffFolder='du -sh'

### To Programming ###

alias findpdb='grep -r "pdb" * | grep -v "#" | cut -d :  -f 1 | sort | uniq | grep ".py$"'
alias findipdb='grep -r "ipdb" * | grep -v "#" | cut -d :  -f 1 | sort | uniq | grep ".py$"'
alias psaux='ps aux | grep -v grep | grep'

function while_true() {
  while true; do $@; read; clear; done
}

function bump_version() {
  yarn version --new-version $1 --no-commit-hooks --no-git-tag-version
  git add package.json
  git commit -m 'chore(package): bump version'
}
# add WEBOS CLI
# WEBOS_CLI_TV="/opt/webOS_TV_SDK/CLI/bin"
# export PATH="$WEBOS_CLI_TV:$PATH"


export PATH="/usr/local/sbin:$PATH"

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
export PATH="$PATH:$HOME/.rvm/bin"

export HOMEBREW_AUTO_UPDATE_SECS="86400"



# pnpm
export PNPM_HOME="/Users/paulooliveira/Library/pnpm"
case ":$PATH:" in
  *":$PNPM_HOME:"*) ;;
  *) export PATH="$PNPM_HOME:$PATH" ;;
esac
# pnpm end

# Fig post block. Keep at the bottom of this file.
[[ -f "$HOME/.fig/shell/zshrc.post.zsh" ]] && builtin source "$HOME/.fig/shell/zshrc.post.zsh"
